# Generated by Django 2.2.4 on 2019-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_grupo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('lineas', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
