# Generated by Django 2.2.4 on 2019-08-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semillero',
            options={'ordering': ['id'], 'verbose_name': 'Semillero', 'verbose_name_plural': 'Semilleros'},
        ),
    ]
