# Generated by Django 2.2.4 on 2019-08-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190809_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='semillero',
            name='lineas',
        ),
        migrations.RemoveField(
            model_name='semillero',
            name='nombre',
        ),
        migrations.AddField(
            model_name='semillero',
            name='id_group',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='lines',
            field=models.CharField(max_length=50, null=True, verbose_name='Líneas de investigación'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del semillero'),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
