# Generated by Django 2.2.4 on 2019-08-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190809_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='id_group',
        ),
        migrations.RemoveField(
            model_name='semillero',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='semillero',
            name='name',
        ),
        migrations.AddField(
            model_name='semillero',
            name='id_grupo',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='lineas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
