# Generated by Django 2.2.4 on 2019-08-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190809_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del integrante')),
                ('document', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Documento de identidad')),
                ('rol', models.PositiveSmallIntegerField(null=True, verbose_name='Rol')),
                ('joined', models.DateTimeField(null=True, verbose_name='Fecha de ingreso')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('career', models.TextField(null=True, verbose_name='Programa de pregrado')),
                ('level', models.PositiveSmallIntegerField(null=True, verbose_name='Nivel en el programa')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['-joined'],
            },
        ),
    ]
