# Generated by Django 2.2.4 on 2019-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_convocatoria_linea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semillero',
        ),
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-opened'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='closed',
            field=models.DateField(null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='opened',
            field=models.DateField(null=True, verbose_name='Fecha de apertura'),
        ),
    ]
