# Generated by Django 2.2.4 on 2019-08-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190813_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convocatoria',
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
    ]
