# Generated by Django 2.2.4 on 2019-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20190813_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre del grupo:')),
                ('coordinator', models.CharField(max_length=50, null=True, verbose_name='Coordinador(a) del grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
    ]
