# Generated by Django 2.2.4 on 2020-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190907_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Título')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
                ('content', models.TextField(null=True, verbose_name='Contenido de la noticia')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre:'),
        ),
    ]
