# Generated by Django 2.2.4 on 2020-01-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200126_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
