# Generated by Django 2.2.4 on 2020-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.FileField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
