# Generated by Django 2.2.4 on 2020-01-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_noticia_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='img',
            new_name='image',
        ),
    ]
