# Generated by Django 2.2.4 on 2020-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200127_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='image',
        ),
        migrations.AddField(
            model_name='noticia',
            name='documento',
            field=models.FileField(null=True, upload_to='', verbose_name='Documento'),
        ),
    ]
