# Generated by Django 2.2.4 on 2020-01-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200127_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='documento',
            new_name='image',
        ),
    ]
