# Generated by Django 2.2.4 on 2020-01-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200127_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='banner',
            field=models.FileField(null=True, upload_to='', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
