# Generated by Django 2.2.4 on 2020-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200130_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
