# Generated by Django 2.2.4 on 2019-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('id_group', models.CharField(max_length=50, null=True, verbose_name='Grupo')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('lines', models.CharField(max_length=50, null=True, verbose_name='Líneas de investigación')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Semillero',
                'verbose_name_plural': 'Semilleros',
                'ordering': ['id'],
            },
        ),
    ]
