# Generated by Django 2.2.4 on 2019-08-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_auto_20190817_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Pregrado',
                'verbose_name_plural': 'Pregrados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del integrante')),
                ('document', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Documento de identidad')),
                ('semillero', models.CharField(max_length=100, null=True, verbose_name='Semillero')),
                ('rol', models.PositiveSmallIntegerField(null=True, verbose_name='Rol')),
                ('joined', models.DateField(null=True, verbose_name='Fecha de ingreso')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('career', models.CharField(max_length=50, null=True, verbose_name='Programa de pregrado')),
                ('level', models.PositiveSmallIntegerField(null=True, verbose_name='Nivel en el programa')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['-joined'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Linea de investigación')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='semillero',
            name='lines',
        ),
        migrations.CreateModel(
            name='LineaSemillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Linea de investigación')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('id_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero')),
            ],
            options={
                'verbose_name': 'Línea por semillero',
                'verbose_name_plural': 'Líneas por semillero',
                'ordering': ['-created'],
            },
        ),
    ]
