# Generated by Django 2.2.4 on 2019-09-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20190827_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineasemillero',
            name='description',
        ),
        migrations.AddField(
            model_name='lineasemillero',
            name='id_linea',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Id de la línea'),
        ),
        migrations.AlterField(
            model_name='lineasemillero',
            name='id_sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Id del semillero'),
        ),
    ]
