# Generated by Django 2.2.4 on 2020-03-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_lineasemillero_id_coo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineasemillero',
            name='id_sem',
        ),
    ]
