# Generated by Django 2.2.4 on 2020-03-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20200313_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineasemillero',
            name='id_coo',
        ),
    ]
