# Generated by Django 2.2.4 on 2020-03-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_auto_20200313_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineasemillero',
            name='id_sem',
        ),
    ]
