# Generated by Django 2.2.4 on 2020-03-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_remove_lineasemillero_id_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del integrante'),
        ),
    ]
