# Generated by Django 2.2.4 on 2020-04-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0015_lineasemillero_id_coo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineasemillero',
            options={'ordering': ['-created'], 'verbose_name': 'Línea por coordinador', 'verbose_name_plural': 'Líneas por coordinador'},
        ),
    ]
