# Generated by Django 2.0.2 on 2020-07-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0017_auto_20200511_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nivel', models.CharField(max_length=10, null=True, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['id'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='career',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lineasemillero',
            name='name',
        ),
        migrations.AddField(
            model_name='career',
            name='tipo',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='aditional',
            field=models.CharField(max_length=100, null=True, verbose_name='Informacion Adicional'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='lineasemillero',
            name='id_linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Linea', verbose_name='Id de la línea'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Career', verbose_name='Programa'),
        ),
    ]
