# Generated by Django 2.0.2 on 2020-07-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0018_auto_20200707_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('joined', models.DateField(null=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Participantes',
                'verbose_name_plural': 'Participantes',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['-id'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='semillero',
        ),
        migrations.AddField(
            model_name='participante2',
            name='id_integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Integrante'),
        ),
        migrations.AddField(
            model_name='participante2',
            name='id_semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Semillero'),
        ),
        migrations.AddField(
            model_name='participante2',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Rol', verbose_name='Rol'),
        ),
    ]
