# Generated by Django 2.0.2 on 2020-07-16 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create', '0019_auto_20200716_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('document', models.CharField(max_length=12, null=True, verbose_name='Documento de identidad')),
                ('id_semillero', models.CharField(max_length=100, null=True, verbose_name='Semillero')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinadores',
                'verbose_name_plural': 'Coordinador',
                'ordering': ['id'],
            },
        ),
    ]
