# Generated by Django 2.0.2 on 2020-07-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0020_coordinadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinadores',
            options={'ordering': ['id'], 'verbose_name': 'Coordinador', 'verbose_name_plural': 'Coordinadores'},
        ),
        migrations.AlterModelOptions(
            name='participante2',
            options={'ordering': ['id'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RemoveField(
            model_name='coordinadores',
            name='document',
        ),
        migrations.AddField(
            model_name='coordinadores',
            name='Integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='Integrante'),
        ),
    ]
