# Generated by Django 2.0.2 on 2020-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0021_auto_20200716_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellidos del integrante'),
        ),
    ]
