# Generated by Django 2.0.2 on 2020-07-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0022_integrante_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Integrante', verbose_name='coordinador'),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='id_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Grupo', verbose_name='Grupo de investigacion'),
        ),
    ]
