# Generated by Django 2.0.2 on 2020-07-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0024_atributos_id_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineasemillero',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante'),
        ),
    ]
