# Generated by Django 2.0.2 on 2020-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0026_auto_20200819_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='Descripción'),
        ),
    ]
