# Generated by Django 2.0.2 on 2020-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0027_semillero_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillero',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/logo_udea.png', null=True, upload_to='', verbose_name='Imagen del semillero'),
        ),
    ]
