# Generated by Django 2.0.2 on 2020-09-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0029_auto_20200929_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributos_otra',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Participante2', verbose_name='Participante'),
        ),
    ]
