# Generated by Django 2.0.2 on 2020-11-15 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0017_auto_20200916_1658'),
        ('create', '0030_atributos_otra_id_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaAdyacente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.TextField(max_length=400, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Adyacente',
                'verbose_name_plural': 'Categorias Adyacentes de produccion cientifica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='categoriaPrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.TextField(max_length=400, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Principal',
                'verbose_name_plural': 'Categorias Principales de produccion cientifica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo adjunto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.categoriaAdyacente', verbose_name='Categoria adyacente')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos', verbose_name='Proyecto Asociado')),
                ('semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.Semillero', verbose_name='Semillero')),
            ],
            options={
                'verbose_name': 'Produccion Cientifica',
                'verbose_name_plural': 'Producciones Cientificas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='categoriaadyacente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.categoriaPrincipal', verbose_name='Categoria Principal'),
        ),
    ]
