# Generated by Django 2.0.2 on 2021-01-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0031_auto_20201115_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('descripcion', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='año',
            field=models.CharField(max_length=100, null=True, verbose_name='Año de publicación'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Mes', verbose_name='Mes de publicación'),
        ),
    ]
