# Generated by Django 2.2.4 on 2019-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='documents',
            field=models.FileField(null=True, upload_to='projects', verbose_name='Documentos'),
        ),
    ]
