# Generated by Django 2.2.4 on 2019-08-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0002_convocatoria_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='documents',
        ),
    ]
