# Generated by Django 2.2.4 on 2019-08-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0003_remove_convocatoria_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['closed'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
    ]
