# Generated by Django 2.0.2 on 2020-07-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0007_auto_20200709_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_adjunto',
            name='id_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Participante', verbose_name='Participante'),
        ),
    ]
