# Generated by Django 2.0.2 on 2020-08-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0008_auto_20200709_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(max_length=10, null=True, verbose_name='Estado'),
        ),
    ]
