# Generated by Django 2.0.2 on 2020-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0009_participante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_adjunto',
            name='comentarios',
            field=models.FileField(null=True, upload_to='', verbose_name='Comentarios'),
        ),
    ]
