# Generated by Django 2.0.2 on 2020-08-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0026_auto_20200819_0419'),
        ('conv', '0010_auto_20200820_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipo', models.CharField(max_length=10, null=True, verbose_name='Tipo')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('codigo', models.CharField(max_length=100, null=True, verbose_name='Codigo')),
                ('porcentaje', models.CharField(max_length=20, null=True, verbose_name='Porcentaje de avance')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Convocatoria')),
                ('semillero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create.Semillero')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='documentos_proyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos'),
        ),
    ]
