# Generated by Django 2.0.2 on 2020-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0011_auto_20200821_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos_proyecto',
            options={'ordering': ['id'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos de proyecto'},
        ),
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(max_length=10, null=True, verbose_name='Estado'),
        ),
    ]
