# Generated by Django 2.0.2 on 2020-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0012_auto_20200902_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='closed',
            field=models.DateField(null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='start',
            field=models.DateField(null=True, verbose_name='Fecha de inicio'),
        ),
    ]
