# Generated by Django 2.0.2 on 2020-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0013_auto_20200910_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_proyecto',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='Descripción'),
        ),
    ]
