# Generated by Django 2.0.2 on 2020-09-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0014_documentos_proyecto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_proyecto_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Proyectos')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos de proyecto',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentos_proyecto',
            options={'ordering': ['id'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes de proyecto'},
        ),
        migrations.RemoveField(
            model_name='documentos_proyecto',
            name='description',
        ),
    ]
