# Generated by Django 2.0.2 on 2020-09-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0015_auto_20200911_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.TextField(max_length=400, null=True, verbose_name='Descripción')),
                ('documento', models.FileField(null=True, upload_to='', verbose_name='Documento')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conv.Documentos_proyecto')),
            ],
            options={
                'verbose_name': 'Observacion',
                'verbose_name_plural': 'Observaciones a reporte',
                'ordering': ['id'],
            },
        ),
    ]
